=== hakiour/proyectox/xml/noticias.dtd
<!DOCTYPE noticias
[
<!ELEMENT noticias (noticia+)>
<!ELEMENT noticias (titulo,subtitulo,imagen,descripcion,link)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT link (#PCDATA)>
]>

=== hakiour/proyectox/xml/noticias.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE noticias SYSTEM "noticias.dtd">
<noticias>
  <noticia>
    <titulo>¿Por qué un DTD?</titulo>
    <subtitulo>Asegurando el correcto formato de nuestras noticias.</subtitulo>
    <imagen>dtd.png</imagen>
    <descripcion>Para asegurar que todos nuestros empleados siguen un formato adecuado a la hora de crear nuevas noticias, se ha creado un DTD que valida el xml, permitiendo que un usuario sin conocimientos avanzados pueda añadir noticias, sabiendo que si se equivoca, el DTD le indicara donde ha fallado.</descripcion>
    <link>dtd.html</link>
  </noticia>
  <noticia>
    <titulo>¿Qué es la tecnología Java y para qué lo necesitamos?</titulo>
    <subtitulo>Java como lenguaje de programación</subtitulo>
    <imagen>queEsJava.png</imagen>
    <descripcion>Java es un lenguaje de programación y una plataforma informática comercializada por primera vez en 1995 por Sun Microsystems.</descripcion>
    <link>queEsJava.html</link>
  </noticia>
  <noticia>
    <titulo>Conceptos útiles y glosario de definiciones</titulo>
    <subtitulo>Conceptos y términos para usuarios inexpertos</subtitulo>
    <imagen>aprendeJava.png</imagen>
    <descripcion> Definición de los diferentes conceptos de Java que cualquier usuario que pretende adentrarse en este maravilloso mundo...</descripcion>
    <link>conceptosUtiles.html</link>
  </noticia>
</noticias>
